spring:
  config:
    activate:
      on-profile: prod
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
    show-sql: ${JPA_SHOW_SQL:false}
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
